<?xml version="1.0" encoding="utf-8"?><Database Name="midtermLogin" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-GT966OV\SQLEXPRESS01;Initial Catalog=midtermLogin;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False" SettingsObjectName="midterm.Properties.Settings" SettingsPropertyName="midtermLoginConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Table_Product" Member="Table_Products">
    <Type Name="Table_Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[No of Stock]" Member="No_of_Stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="[Selling Price]" Member="Selling_Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Table_Product_Table_Transaction" Member="Table_Transactions" ThisKey="ProductID" OtherKey="ProductID" Type="Table_Transaction" />
    </Type>
  </Table>
  <Table Name="dbo.Table_Transaction" Member="Table_Transactions">
    <Type Name="Table_Transaction">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TransactionType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Table_Product_Table_Transaction" Member="Table_Product" ThisKey="ProductID" OtherKey="ProductID" Type="Table_Product" IsForeignKey="true" />
      <Association Name="Table_User_Table_Transaction" Member="Table_User" ThisKey="UserID" OtherKey="UserID" Type="Table_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table_User" Member="Table_Users">
    <Type Name="Table_User">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Table_User_Table_Transaction" Member="Table_Transactions" ThisKey="UserID" OtherKey="UserID" Type="Table_Transaction" />
    </Type>
  </Table>
</Database>